### ISSUE TITLE
clk.parameter.show does not display preset content

### ISSUE THREAD

**Issue by sjoubert** [clk-project/clk#37]
When calling `[clk] parameter show` I'm not seeing any parameter values coming from any of my preset or the default clk preset. 

* This also seems to happen with `trigger` but not `value` or `launcher` (not tested any other similar concept like `alias`)
* Tested with `globalpreset_profile`, `localpreset_profile` and `currentdirectorypreset_profile` (`global` and `local` profile data are correctly displayed though)
* The data seems to be correctly used, just not displayed in the `show` sub-command

Not sure if it matters, but I'm not using `clk` directly but my own cli based on it. It has its own `Config(BaseConfig)` object that overrides the global and currentdirectory presets.

**Comment by Konubinix** [comment]
Hi,

Sylvain Joubert ***@***.***> writes:

> When calling `[clk] parameter show` I'm not seeing any parameter values coming from any of my preset or the default clk preset.
>
> * This also seems to happen with `trigger` but not `value` or `launcher` (not tested any other similar concept like `alias`)
> * Tested with `globalpreset_profile`, `localpreset_profile` and `currentdirectorypreset_profile` (`global` and `local` profile data are correctly displayed though)
> * The data seems to be correctly used, just not displayed in the `show` sub-command

You can see it using ~clk parameter show --full~ it is deliberately
hidden from the command by default because it is not what we want 90% of
the time.

If you don't like that behavior, you can obviously change that setting using ~clk parameter set parameter.show --full~

> Not sure if it matters, but I'm not using `clk` directly but my own cli based on it. It has its own `Config(BaseConfig)` object that overrides the global and currentdirectory presets.

Creating your own cli is a feature I would like to make easier. I'm glad
you could do so. Can you share how you did that so that I can derive a
documentation from it. I already have something
(https://clk-project.org/doc/use_cases/rolling_your_own.html), but I
feel like with your input, it might become even better.

In particular, can you share what your new config looks like?

My best,
-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

**Comment by Konubinix** [comment]
By the way, you are mentionning trigger. Do you use those?

**Comment by Konubinix** [comment]
Thank you for your answer. Creating your own tool is indeed a good way to change the defaults, that are, like the doc says "very opinionated".

About the defaults, I would totally love to change my mind, so please tell me your opinion, shall time permits.

About creating your own tool, did you know that clk was first intended at being a library, like click, but with more "batteries included"? Then the command line tool "clk" was born, and now I use it intensely. But we are still envisionning the library use case. This is why we have the `clk fork` command after all.

Therefore, I would be very grateful if you shared you experience if at some point you created a command line tool out of clk. We expect the developer experience to be shitty for now, and it is only thanks to people like you that it can become nice over time.

**Comment by Konubinix** [comment]
Is there anything else you want to add or shall we close that issue ?

**Comment by sjoubert** [comment]
If you are _very opiniately_ ( :wink: ) ok with the different behavior between the similar sub-commands, you can close it.
In any case, I'm ok on my side, I'll force it in the global preset of my tool using the `--full` option as needed.

**Comment by Konubinix** [comment]
Sylvain Joubert ***@***.***> writes:

> If you are _very opiniately_ ( :wink: ) ok with the different behavior
> between the similar sub-commands, you can close it.

The subject of this issue was about the behavior of parameter only. The
uniformity of behavior with other commands appears to have been only a
side note. Therefore, I did not think you wanted to address this matter
here.

I think the main cause of difference is that those commands appeared at
different periods. I don't mind at all changing them.

The opinionated part is more into the "reasons to believe".

I believe that uniformity alone is not a good design decision here. They
fit in different scenarios that may have different base assumptions, and
a behavior that makes sense for one not necessarily makes sense for
another.

I also believe that only real life usage can capture the idea of "what
it feels like" to use a command. In that sense, I think what we need is
anecdotes of using those commands explaining how they fit into a real
life situation. Those anecdotes can be converted into documentations and
tests driving the design and the implementation of those commands.

For instance, because you have no experience with using "trigger", I
doubt your opinion or any story you can come up with, however convincing
in theory, would be of much value.

But if you tell us your story in which you used parameter, I think that
would help understand why showing the preset values by default could be
a good idea. Like I said, "it is not what we want 90% of the time", but
that is 90% of the stories I know about (most of them from personal
experience). Adding yours will help decreasing this number and maybe in
time help changing the default behavior.

The same goes for the other commands you used, like maybe alias? Tell us
your story, this is what brings the most value.

Again, don't invent use cases, like "Given that situation, When Alice
does X, Then Y happens". Those feel true on paper but lead to poor UX (I
think). Only tell us about real life usages and what is the behavior you
expected in those. Prefer stuff like "I am in that situation. I want to
reach the goal G, therefore I use clk in the way X. Let me show you how
in that case Y happens and how that actually helps me". I know that it
is an exercise much more cognitively demanding than the alternative, but
I totally think it is worth it.

-- 
Konubinix GPG Key : 7439106A Fingerprint: 5993 BE7A DA65 E2D9 06CE 5C36
75D2 3CED 7439 106A

**Comment by Konubinix** [comment]
Just to let you know. I finally enabled the display of preset values by default in clk parameter. I'm still not convinced by your arguments, but I don't have any strong reason to show them or hide them by default. On the other hand, you appear to like it that way, and it does not annoy me at all, so why not changing the default behavior? It is available in the version 38 of clk.
